name: Custom Action
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run: echo "Hello"

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Print Files 1.sh
      run: |
        touch file1 file2 file3
        ls
        echo "Current directory: $PWD"
        cat 1
        cat 2
