name: Custom Action
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run: echo "Hello"

  job2:
  runs-on: ubuntu-latest
  steps:
  - name: Print Files 1 and 2
    run: ls
  - name: Print Current Directory
    run: echo "Current directory: $PWD"
  - name: Print File 1 Contents
    run: cat 1
  - name: Print File 2 Contents
    run: cat 2
